exec swaybg -i ~/.config/sway/wallpapers/kde-wallpaper2.png -m fill
exec mako
exec waybar
exec Xwayland :1 &
exec nm-applet
exec blueman-applet
# exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec --no-startup-id dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec --no-startup-id /usr/lib/xdg-desktop-portal-wlr &
exec --no-startup-id /usr/lib/xdg-desktop-portal -r

exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -f -c 000000'
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.
