exec-once = waybar
exec-once = swaybg -i ~/.config/hypr/wallpapers/kde-wallpaper1.png -m fill
exec-once = nm-applet

exec-once = swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -f -c 000000'
